LOAD DATA LOCAL INFILE './EbayUser.csv' 
  INTO TABLE EbayUser
  FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
	ESCAPED BY '"';
    
LOAD DATA LOCAL INFILE './Category.csv' 
  INTO TABLE Category
  FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
	ESCAPED BY '"';
	
LOAD DATA LOCAL INFILE './Item.csv' 
  INTO TABLE Item
  FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
	ESCAPED BY '"';
	
LOAD DATA LOCAL INFILE './ItemCategory.csv' 
  INTO TABLE ItemCategory
  FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
	ESCAPED BY '"';
	
LOAD DATA LOCAL INFILE './Bid.csv' 
  INTO TABLE Bid
  FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
	ESCAPED BY '"';